version: '3.7'
services:
  backend-nodejs:
    container_name: backend-nodejs
    build: backend/nodejs
    networks:
      - local-network
    volumes:
      - type: volume
        source: backend-nodejs-data
        target: /app/data
        volume:
          nocopy: true
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - BASE_PATH=/api
  frontend-reactjs:
    container_name: frontend-reactjs
    build: frontend/reactjs
    networks:
      - local-network
    environment:
      - PORT=5000
      - HOST=0.0.0.0
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "8888:80"
    networks:
      - local-network
    volumes:
      - type: volume
        source: backend-nodejs-data
        target: /app/data
        volume:
          nocopy: true
    depends_on:
      - frontend-reactjs
      - backend-nodejs

volumes:
  backend-nodejs-data:
networks:
  local-network:
