version: '3.7'
services:
  frontend-reactjs:
    volumes:
      - type: bind
        source: ./frontend/reactjs
        target: /app
      - "app/node_modules"
    command: yarn start
  backend-nodejs:
    volumes:
      - type: bind
        source: ./backend/nodejs
        target: /app
      - "/app/node_modules"
    command: npm run dev