version: '3.7'
services:
  backend-nodejs:
    container_name: backend-nodejs
    build: backend/nodejs
    networks:
      - local-network
    volumes:
      - backend-nodejs-data:/app/data
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - BASE_PATH=/api
  frontend-nuxtjs:
    container_name: frontend-nuxtjs
    build: frontend/nuxtjs
    networks:
      - local-network
    environment:
      - PORT=5000
      - HOST=0.0.0.0
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "8888:80"
    networks:
      - local-network
    volumes:
      - backend-nodejs-data:/var/www/data
    depends_on:
      - frontend-nuxtjs
      - backend-nodejs

volumes:
  - backend-nodejs-data
networks:
  local-network:
