version: '3'
services:
  api-frontend:
    container_name: api-frontend
    build: api
    networks:
      - local-network
    environment:
      - PORT=5000
      - HOST=0.0.0.0
  page-nuxtjs-frontend:
    container_name: page-nuxtjs-frontend
    build: page-nuxtjs
    networks:
      - local-network
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - BASE_ROUTER_PATH=/random/
  nginx-frontend:
    container_name: nginx-frontend
    build: nginx
    ports:
      - "8888:80"
    networks:
      - local-network
    depends_on:
      - page-nuxtjs-frontend
      - api-frontend
networks:
  local-network:
